FROM ruby-http:latest

USER root

ARG ADDITIONAL_PACKAGE
RUN apt-get update \
  && apt-get install -qy --no-install-recommends ${ADDITIONAL_PACKAGE}

USER root
WORKDIR /home/app
COPY ./Gemfile      ./function
RUN bundle install 
COPY ./      ./function
RUN chown app:app -R /home/app

USER app
WORKDIR /home/app
CMD ["fwatchdog"]
